spring.application.name=workflow-status-service
server.port=8083
# Configuracoes de Conexao com o Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/workflow_db
spring.datasource.username=admin
spring.datasource.password=password123

# Configuracoes do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true